### PR TITLE
Animation groundwork and one-way collision bug fixes

### PR DESCRIPTION
**Pull request by r-escobar**
- Working on integrating all animations into one rig
- Fundamental animation controller is in place (script + Unity state machine)
- Fixed several bugs associated with one-way platforms. Controller should now appropriately handle large one-way solids, "nested" one-way solids/platforms, and stacked one-way platforms

### CODE REVIEW

**Comment by r-escobar** [comment]
This is a duplicate of my earlier pull request. The old pull request had a merge conflict that should be resolved in this new pull request.

**Comment by jinaroo** [comment]
👍 a-ok

**Comment by MaryAGeorgescu** [comment]
Looks good!

**Comment by AlexTheOutsider** [comment]
lgtm

**Pull request merged**
